export const roomUiText = {
    fill_all_fields: {
      pt: "Preencha todos os campos.",
      en: "Fill in all fields.",
      es: "Completa todos los campos.",
      fr: "Remplissez tous les champs.",
    },
    current_password_incorrect: {
      pt: "Senha atual incorreta.",
      en: "Current password is incorrect.",
      es: "La contraseña actual es incorrecta.",
      fr: "Le mot de passe actuel est incorrect.",
    },
    password_updated: {
      pt: "Senha trocada com sucesso.",
      en: "Password updated successfully.",
      es: "Contraseña actualizada con éxito.",
      fr: "Mot de passe mis à jour avec succès.",
    },
    password_update_unavailable: {
      pt: "Nao foi possivel atualizar a senha.",
      en: "Unable to update the password.",
      es: "No fue posible actualizar la contraseña.",
      fr: "Impossible de mettre à jour le mot de passe.",
    },
    remove_player_error: {
      pt: "Nao foi possivel remover o jogador.",
      en: "Unable to remove player.",
      es: "No fue posible eliminar al jugador.",
      fr: "Impossible de supprimer le joueur.",
    },
    photo_send_error: {
      pt: "Nao foi possivel enviar a foto.",
      en: "Unable to send the photo.",
      es: "No fue posible enviar la foto.",
      fr: "Impossible d'envoyer la photo.",
    },
    score_update_error: {
      pt: "Nao foi possivel atualizar o placar.",
      en: "Unable to update the score.",
      es: "No fue posible actualizar el marcador.",
      fr: "Impossible de mettre a jour le score.",
    },
    end_race_error: {
      pt: "Nao foi possivel encerrar a corrida.",
      en: "Unable to end the race.",
      es: "No fue posible terminar la carrera.",
      fr: "Impossible de terminer la course.",
    },
    claim_enter_code: {
      pt: "Digite o codigo.",
      en: "Enter the code.",
      es: "Ingresa el codigo.",
      fr: "Entrez le code.",
    },
    claim_register_error: {
      pt: "Erro ao registrar.",
      en: "Registration error.",
      es: "Error al registrar.",
      fr: "Erreur lors de l'enregistrement.",
    },
    claim_register_unavailable: {
      pt: "Nao foi possivel registrar o avatar.",
      en: "Unable to register the avatar.",
      es: "No fue posible registrar el avatar.",
      fr: "Impossible d'enregistrer l'avatar.",
    },
    claim_registered_success: {
      pt: "Avatar registrado com sucesso.",
      en: "Avatar registered successfully.",
      es: "Avatar registrado con exito.",
      fr: "Avatar enregistre avec succes.",
    },
    claim_prompt_label: {
      pt: "Codigo de resgate",
      en: "Claim code",
      es: "Codigo de canje",
      fr: "Code de redemption",
    },
    claim_prompt_placeholder: {
      pt: "EX: BETA-2025-01",
      en: "E.g. BETA-2025-01",
      es: "Ej: BETA-2025-01",
      fr: "Ex: BETA-2025-01",
    },
    recovery_email_label: {
      pt: "E-mail de recuperacao",
      en: "Recovery email",
      es: "Correo de recuperacion",
      fr: "E-mail de recuperation",
    },
    recovery_email_placeholder: {
      pt: "voce@email.com",
      en: "you@email.com",
      es: "tu@email.com",
      fr: "vous@email.com",
    },
    recovery_email_save_error: {
      pt: "Nao foi possivel salvar o e-mail.",
      en: "Could not save the email.",
      es: "No se pudo guardar el correo.",
      fr: "Impossible d'enregistrer l'e-mail.",
    },
    recovery_email_saved: {
      pt: "E-mail de recuperacao salvo.",
      en: "Recovery email saved.",
      es: "Correo de recuperacion guardado.",
      fr: "E-mail de recuperation enregistre.",
    },
    update_btn: {
      pt: "Atualizar",
      en: "Update",
      es: "Actualizar",
      fr: "Mettre a jour",
    },
    save_btn: {
      pt: "Salvar",
      en: "Save",
      es: "Guardar",
      fr: "Enregistrer",
    },
    welcome_premium_error: {
      pt: "Nao foi possivel liberar o avatar premium.",
      en: "Unable to unlock premium avatar.",
      es: "No fue posible desbloquear el avatar premium.",
      fr: "Impossible de debloquer l'avatar premium.",
    },
    welcome_premium_title: {
      pt: "Boa noticia! Voce pode desbloquear um avatar premium!",
      en: "Good news! You can unlock one premium avatar!",
      es: "Buenas noticias! Puedes desbloquear un avatar premium!",
      fr: "Bonne nouvelle ! Vous pouvez debloquer un avatar premium !",
    },
    welcome_premium_claimed_prefix: {
      pt: "Avatares premium resgatados",
      en: "Claimed premium avatars",
      es: "Avatares premium reclamados",
      fr: "Avatars premium recuperes",
    },
    welcome_premium_choose_later: {
      pt: "Escolher depois",
      en: "Choose later",
      es: "Elegir despues",
      fr: "Choisir plus tard",
    },
    welcome_premium_confirm_title: {
      pt: "Confirmar desbloqueio",
      en: "Confirm unlock",
      es: "Confirmar desbloqueo",
      fr: "Confirmer le debloquage",
    },
    welcome_premium_confirm_message: {
      pt: "Deseja desbloquear um avatar premium? Esta escolha nao pode ser desfeita.",
      en: "Unlock this premium avatar? This choice cannot be undone.",
      es: "Quieres desbloquear este avatar premium? Esta eleccion no se puede deshacer.",
      fr: "Voulez-vous debloquer cet avatar premium ? Ce choix est definitif.",
    },
    welcome_premium_confirm_cancel: {
      pt: "Cancelar",
      en: "Cancel",
      es: "Cancelar",
      fr: "Annuler",
    },
    welcome_premium_confirm_unlock: {
      pt: "Desbloquear avatar",
      en: "Unlock avatar",
      es: "Desbloquear avatar",
      fr: "Debloquer avatar",
    },
    premium_credits_available: {
      pt: "Créditos premium disponíveis: {count}",
      en: "Premium credits available: {count}",
      es: "Créditos premium disponibles: {count}",
      fr: "Crédits premium disponibles : {count}",
    },
    invitation_code_label: {
      pt: "Código de convite",
      en: "Invitation code",
      es: "Código de invitación",
      fr: "Code d'invitation",
    },
  } as const;