export const homeUiText = {
    create_account_success: {
      pt: "Conta criada com sucesso!",
      en: "Account created successfully!",
      es: "Cuenta creada con Ã©xito!",
      fr: "Compte crÃ©Ã© avec succÃ¨s !",
    },
    login_error: {
      pt: "Erro ao entrar. Tente novamente.",
      en: "Unable to log in. Please try again.",
      es: "Error al iniciar sesiÃ³n. IntÃ©ntalo de nuevo.",
      fr: "Erreur de connexion. RÃ©essayez.",
    },
    claim_enter_code: {
      pt: "Digite o codigo.",
      en: "Enter the code.",
      es: "Ingresa el cÃ³digo.",
      fr: "Entrez le code.",
    },
    claim_register_error: {
      pt: "Erro ao registrar.",
      en: "Registration error.",
      es: "Error al registrar.",
      fr: "Erreur lors de l'enregistrement.",
    },
    claim_register_unavailable: {
      pt: "Nao foi possivel registrar o avatar.",
      en: "Unable to register the avatar.",
      es: "No fue posible registrar el avatar.",
      fr: "Impossible d'enregistrer l'avatar.",
    },
    claim_registered_success: {
      pt: "Avatar registrado com sucesso.",
      en: "Avatar registered successfully.",
      es: "Avatar registrado con exito.",
      fr: "Avatar enregistre avec succes.",
    },
    claim_prompt_label: {
      pt: "Codigo de resgate",
      en: "Claim code",
      es: "Codigo de canje",
      fr: "Code de redemption",
    },
    claim_prompt_placeholder: {
      pt: "EX: BETA-2025-01",
      en: "E.g. BETA-2025-01",
      es: "Ej: BETA-2025-01",
      fr: "Ex: BETA-2025-01",
    },
    fill_all_fields: {
      pt: "Preencha todos os campos.",
      en: "Fill in all fields.",
      es: "Completa todos los campos.",
      fr: "Remplissez tous les champs.",
    },
    current_password_incorrect: {
      pt: "Senha atual incorreta.",
      en: "Current password is incorrect.",
      es: "La contraseÃ±a actual es incorrecta.",
      fr: "Le mot de passe actuel est incorrect.",
    },
    password_updated: {
      pt: "Senha trocada com sucesso.",
      en: "Password updated successfully.",
      es: "ContraseÃ±a actualizada con Ã©xito.",
      fr: "Mot de passe mis Ã  jour avec succÃ¨s.",
    },
    password_update_unavailable: {
      pt: "Nao foi possivel atualizar a senha.",
      en: "Unable to update the password.",
      es: "No fue posible actualizar la contraseÃ±a.",
      fr: "Impossible de mettre Ã  jour le mot de passe.",
    },
    login_required_photo: {
      pt: "VocÃª precisa estar logado para o modo foto.",
      en: "You must be logged in to use photo mode.",
      es: "Debes iniciar sesiÃ³n para usar el modo foto.",
      fr: "Vous devez Ãªtre connectÃ© pour utiliser le mode photo.",
    },
    create_room_error: {
      pt: "Erro ao criar sala.",
      en: "Unable to create room.",
      es: "No se pudo crear la sala.",
      fr: "Impossible de crÃ©er la salle.",
    },
    join_room_error: {
      pt: "Erro ao entrar na sala.",
      en: "Unable to join the room.",
      es: "Error al entrar a la sala.",
      fr: "Impossible de rejoindre la salle.",
    },
    recovery_email_reminder: {
      pt: "Adicione um e-mail de recuperaÃ§Ã£o para sua seguranÃ§a. Clique na engrenagem para configurar.",
      en: "Add a recovery email for your safety. Click the gear to set it up.",
      es: "Agrega un correo de recuperaciÃ³n para tu seguridad. Haz clic en el engranaje para configurarlo.",
      fr: "Ajoutez un e-mail de rÃ©cupÃ©ration pour votre sÃ©curitÃ©. Cliquez sur l'engrenage pour le configurer.",
    },
    recovery_email_save_error: {
      pt: "NÃ£o foi possÃ­vel salvar o e-mail.",
      en: "Could not save the email.",
      es: "No se pudo guardar el correo.",
      fr: "Impossible d'enregistrer l'e-mail.",
    },
    recovery_email_saved: {
      pt: "E-mail de recuperaÃ§Ã£o salvo.",
      en: "Recovery email saved.",
      es: "Correo de recuperaciÃ³n guardado.",
      fr: "E-mail de rÃ©cupÃ©ration enregistrÃ©.",
    },
    reset_username_email_mismatch: {
      pt: "UsuÃ¡rio e e-mail nÃ£o conferem.",
      en: "Username and email do not match.",
      es: "El usuario y el correo no coinciden.",
      fr: "Le nom d'utilisateur et l'e-mail ne correspondent pas.",
    },
    reset_request_start_error: {
      pt: "NÃ£o foi possÃ­vel iniciar a recuperaÃ§Ã£o agora.",
      en: "Could not start recovery right now.",
      es: "No se pudo iniciar la recuperaciÃ³n ahora.",
      fr: "Impossible de dÃ©marrer la rÃ©cupÃ©ration pour le moment.",
    },
    reset_request_sent: {
      pt: "Se existir uma conta com esse usuÃ¡rio e e-mail, enviamos um cÃ³digo.",
      en: "If an account exists with that username and email, we sent a code.",
      es: "Si existe una cuenta con ese usuario y correo, enviamos un cÃ³digo.",
      fr: "Si un compte existe avec ce nom d'utilisateur et cet e-mail, nous avons envoyÃ© un code.",
    },
    recovery_email_label: {
      pt: "E-mail de recuperaÃ§Ã£o",
      en: "Recovery email",
      es: "Correo de recuperaciÃ³n",
      fr: "E-mail de rÃ©cupÃ©ration",
    },
    recovery_email_placeholder: {
      pt: "voce@email.com",
      en: "you@email.com",
      es: "tu@email.com",
      fr: "vous@email.com",
    },
    update_btn: {
      pt: "Atualizar",
      en: "Update",
      es: "Actualizar",
      fr: "Mettre Ã  jour",
    },
    save_btn: {
      pt: "Salvar",
      en: "Save",
      es: "Guardar",
      fr: "Enregistrer",
    },
    premium_credits_available: {
      pt: "CrÃ©ditos premium disponÃ­veis: {count}",
      en: "Premium credits available: {count}",
      es: "CrÃ©ditos premium disponibles: {count}",
      fr: "CrÃ©dits premium disponibles : {count}",
    },
    referral_applied_success: {
      pt: "CÃ³digo de indicaÃ§Ã£o aplicado! Ambos receberam +1 crÃ©dito premium.",
      en: "Referral code applied! Both accounts received +1 premium credit.",
      es: "Â¡CÃ³digo de referencia aplicado! Ambas cuentas recibieron +1 crÃ©dito premium.",
      fr: "Code de parrainage appliquÃ© ! Les deux comptes ont reÃ§u +1 crÃ©dit premium.",
    },
    referral_applied_error: {
      pt: "NÃ£o foi possÃ­vel aplicar o cÃ³digo de indicaÃ§Ã£o.",
      en: "Could not apply the referral code.",
      es: "No se pudo aplicar el cÃ³digo de referencia.",
      fr: "Impossible d'appliquer le code de parrainage.",
    },
    invitation_code_label: {
      pt: "CÃ³digo de convite",
      en: "Invitation code",
      es: "CÃ³digo de invitaciÃ³n",
      fr: "Code d'invitation",
    },
  } as const;